import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashSider from "./Static/DashSider/DashSider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full md:flex ">
          <div className="hidden md:flex md:fixed z-20 ">
            <DashSider />
          </div>

          <div className="w-full flex justify-end items-center">
            <div className="w-full md:w-[calc(100vw-220px)] bg-red-600 transition-all duration-[350ms]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
